onRegistration/app/urls.py
from django.urls import path, include
from app import views

# Template URLs
app_name = "app"

urlpatterns = [
    path("register/", views.register, name='register'),
    path("user_login/", views.user_login, name="user_login")
]

onRegistration/onRegistration/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("app/", include('app.urls')),
    path("logout/", views.user_logout, name="logout"),
    path("special", views.special, name="special")
]

onRegistration/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,)
    
    # blank=True mean they are optional
    portfolio = models.URLField(blank=True)
    profpic = models.ImageField(upload_to='profile_pictures', blank=True) 
    
    def __str__(self):
        return self.user.username

onRegistration/app/forms.py
from django import forms
from django.contrib.auth.models import User
from app.models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        
class ProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('portfolio', 'profpic')
        

onRegistration/app/views.py
from django.shortcuts import render
from app.forms import UserForm, ProfileForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return render(request, 'app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in.")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = ProfileForm(data=request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            
            profile = profile_form.save(commit=False)
            profile.user = user   # For one to one
            
            if 'profpic' in request.FILES:
                profile.profpic = request.FILES['profpic']
                
            profile.save()
            registered = True
            
        else:
            print(user_form.errors, profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    
    return render(request, 'app/registration.html',
                  {'user_form': user_form,
                   "profile_form": profile_form,
                   "registered": registered})
    

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            
            else:
                return HttpResponse("Account Not Active!")
        else:
            print("Someone tried to login and failed!")
            print(f"Username: {username} and password: {password}")
            return HttpResponse("Invalid Login Details!")
    else:
        return render(request, 'app/login.html', {})
            

onRegistration/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Brand</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'app:register' %}">Register</a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Link
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>

              <li class="nav-item">
                <a class="nav-link disabled">Link</a>
              </li>

              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:user_login' %}">Login</a>
                </li>
              {% endif %}

            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>
    
    <div class="container">
        {% block body_block %}
        {% comment %} Everything outside of this will be inherited if you extend! {% endcomment %}
        {% endblock %}
    </div>
    
</body>
</html>

onRegistration/templates/app/index.html
{% extends 'app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Homepage</h1>
</div>

{% endblock %}

onRegistration/templates/app/login.html
{% extends 'app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Login</h1>
    <form action="{% url 'app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">username:</label>
        <input type="text" name="username" placeholder="username">
        
        <label for="password">Password:</label>
        <input type="password" name='password'>
        
        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

onRegistration/templates/app/registration.html
{% extends 'app/base.html' %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h2>Fill out the form:</h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}